Updated give command to accept k and m in parameter
ChristopherBThai/Discord-OwO-Bot pull request #319
Opened 2022-12-20 15:15 UTC by dibas-np

2023-01-08 08:29 UTC, ChristopherBThai requested changes

2023-01-08 08:29 UTC, ChristopherBThai commented on src/commands/commandList/economy/give.js
> +				if (/[kK]/.test(value) && !amount) {
regex needs to be more specific

2023-01-08 09:20 UTC, dibas-np commented on src/commands/commandList/economy/give.js
> +				if (/[kK]/.test(value) && !amount) {
updated

2023-02-20 05:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChristopherBThai/Discord-OwO-Bot?pullRequest=319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ChristopherBThai/Discord-OwO-Bot?pullRequest=319) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: Caviarbro<br/>:white_check_mark: dibas-np<br/>:white_check_mark: ChristopherBThai<br/>:x: Christopher Thai<br/><hr/>**Christopher Thai** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChristopherBThai/Discord-OwO-Bot?pullRequest=319) it.</sub>

2023-02-20 05:53 UTC, atifnimran approved these changes

2023-02-20 05:57 UTC, atifnimran commented
Hello

2023-04-04 12:46 UTC, closed without merging